# -*- coding: utf-8 -*-
"""bankETL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y_tCZM7seHnRqHgTU9mif3rQ5XCUQYx3
"""

# Importamos Librerias
import pandas as pd

# Mostrar la Base de Datos
bank = pd.read_csv('/content/bank-full.csv')
bank

# Mostrar la primera parte del DataFrame
bank.head()

# Mostrar las estadísticas descriptivas de la columna 'balance'
bank['balance'].describe()

# Filtrar las transacciones aprobadas
bank_approved = bank[bank['y'] == 'yes']
print(bank_approved)

# Agrupar las transacciones por mes y calcular la media de 'balance'
bank_approved.groupby('month').mean(numeric_only=True)['balance']
print(bank_approved)

# Crear la columna 'date' concatenando 'day' y 'month'
bank['date'] = bank['day'].astype(str) + '-' + bank['month']
print(bank)

# Identificar las transacciones más comunes en las que se realiza un préstamo (loan = 1)
bank_loans = bank_approved[bank_approved['loan'] == 'yes']
print(bank_loans)

# Analizar las características de los clientes que realizan préstamos
bank_loans.describe()